### ISSUE TITLE
TraceIDs dispatched are not consistent with IDs produced by tracer

### ISSUE THREAD

**Issue by person-unko** [jonahgeorge/jaeger-client-php#131]
Issue:

TraceIDs sent to Tempo are not consistent with IDs produced by Jaeger tracer. During our code's execution, we add the current traceID from the active span to our log messages, that are then dispatched to Loki. However, these do not match up with the eventual traceIDs dispatched to Tempo.

Config:

Tempo.yaml
```
distributor:
    log_received_traces: true
    receivers:
        jaeger:
            protocols:
                thrift_binary:
```

Docker-compose
```
    tempo:
        image: grafana/tempo:latest
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
            - ./tempo-data:/tmp/tempo
        ports:
            - "6832:6832/udp"    # jaeger compact udp
            - "3102:3102"   # tempo
        networks:
            - my_net
```

Dispatch mode: `JAEGER_OVER_BINARY_UDP`

Example:

Tempo Log:
`2023-09-18 11:57:14 level=info ts=2023-09-18T10:57:14.295262422Z caller=distributor.go:551 msg=received spanid=3c8e8ad1d626a765 traceid=43635777228142443577722814244709`

TraceID logged in our system: `4363577722814244709`

Querying Tempo for the traceID 4363577722814244709 returns a 404, querying with 43635777228142443577722814244709 returns the trace.
